[Makefile]
lexer=makefile

style.33=name:LineNumbers,fore:clBlack,back:clSilver,font:Arial
style.34=name:Ok Braces,fore:clBlue,bold
style.35=name:Bad Braces,fore:clRed,bold
style.36=name:Control Chars,back:clSilver
style.37=name:Indent Guide,fore:clSilver
style.0=name:Default
style.1=name:Comment,fore:clGreen
style.2=name:Pre-processor or other comment,fore:#7F7F00
style.3=name:Variable,fore:#000080
style.4=name:Operator,fore:#B06000
style.5=name:Target,fore:#A00000
style.9=name:Error,fore:clYellow,back:clRed,eolfilled 
style.34=name:Matched Operators 1,fore:#0000FF,notbold
style.35=name:Matched Operators 2,fore:#FF0000,notbold

CommentBoxStart=#
CommentBoxEnd=#
CommentBoxMiddle=#
CommentBlock=#
CommentStreamStart=#
CommentStreamEnd=#
AssignmentOperator==
EndOfStatementOperator=;